apiVersion: v1
kind: Service
metadata:
  labels:
    app: basex
  name: basex-service
spec:
  ports:
    - name: "1984"
      port: 1984
      targetPort: 1984
  selector:
    app: basex
  type: ClusterIP
