{{- if .Values.clamav.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: clamav
  name: clamav-service
spec:
  ports:
    - name: "3310"
      port: 3310
      targetPort: 3310
  selector:
    app: clamav
  type: ClusterIP
{{- end }}
