{{- if .Values.clamav.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clamav
  name: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
        - image: clamav/clamav:1.4.1
          name: clamav
          ports:
            - containerPort: 3310
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: clamavdata
      volumes:
        - name: clamavdata
          persistentVolumeClaim:
            claimName: clamav-pvc
{{- end }}
