apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emakin
  name: emakin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emakin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: emakin
    spec:
      containers:
        - env:
            {{- if .Values.clamav.enabled }}
            - name: AK_AntivirusServerUrl
              value: tcp://clamav:3310
            {{- end }}
            - name: AK_BasexConnStr
              value: http://admin:admin@basex:1984/
            {{- if eq .Values.db.externalConnection "" }}
            - name: AK_DbProvider
              value: PostgreSql
            - name: AK_DbConnStr
              value: Host=postgre;Database={{ .Values.db.name }};Username={{ .Values.db.user }};Password={{ .Values.db.password }};
            {{- else }}
            - name: AK_DbProvider
              value: {{ .Values.db.externalProvider }}
            - name: AK_DbConnStr
              value: {{ .Values.db.externalConnection }};
            {{- end }}
            - name: AK_RedisConnStr
              value: redis,allowAdmin=true
            {{ if .Values.tika.enabled }}
            - name: AK_TikaConnStr
              value: http://tika:9998/
            {{- end }}
            {{ if .Values.onlyoffice.enabled }}
            - name: AK_WopiConnStr
              value: http://onlyoffice/hosting/discovery
            {{- end }}
            - name: AK_DEFAULT_ADMIN
              value: {{ .Values.emakin.admin }}
            - name: AK_DEFAULT_ADMIN_PASSWORD
              value: {{ .Values.emakin.password }}
          image: 6kare/emakin:8.5
          name: emakin
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 7180
              protocol: TCP
            - containerPort: 25
              protocol: TCP
            - containerPort: 587
              protocol: TCP
            - containerPort: 465
              protocol: TCP
            - containerPort: 5121
              protocol: TCP
          volumeMounts:
            - mountPath: /app/Configuration/Data
              name: emakin-data
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: '0'
      volumes:
        - name: emakin-data
          persistentVolumeClaim:
            claimName: emakin-pvc
