apiVersion: v1
kind: Service
metadata:
  labels:
    service: emakin-web
  name: emakin-web
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: emakin
  type: ClusterIP
