apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: emakin-web
spec:
    rules:
        - http:
              paths:
                  - backend:
                        service:
                            name: emakin-web
                            port:
                                number: 80
                    path: /
                    pathType: Prefix
