apiVersion: v1
kind: Service
metadata:
  labels:
    service: emakin-smtp
  name: emakin-smtp
spec:
  ports:
    - name: "25"
      port: 25
      targetPort: 25
    - name: "587"
      port: 587
      targetPort: 587
    - name: "465"
      port: 465
      targetPort: 465
  selector:
    service: emakin
  type: LoadBalancer
