{{- if .Values.emakin.smtp.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emakin
  name: emakin-smtp
spec:
  ports:
    - name: "25"
      port: 25
      targetPort: 25
    - name: "587"
      port: 587
      targetPort: 587
    - name: "465"
      port: 465
      targetPort: 465
  selector:
    app: emakin
  type: LoadBalancer
  externalIPs:
    - {{ .Values.externalIP }}
{{- end }}
