{{- if .Values.onlyoffice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: onlyoffice
  name: onlyoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice
  template:
    metadata:
      labels:
        app: onlyoffice
    spec:
      containers:
        - env:
            - name: USE_UNAUTHORIZED_STORAGE
              value: "true"
            - name: WOPI_ENABLED
              value: "true"
          image: onlyoffice/documentserver:8.0
          name: onlyoffice
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
      restartPolicy: Always
{{- end }}
