{{- if eq .Values.db.externalConnection "" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: postgres-pv-{{ .Values.environment }}
{{- end }}
