{{- if .Values.tika.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tika
  name: tika-service
spec:
  ports:
    - name: "9998"
      port: 9998
      targetPort: 9998
  selector:
    app: tika
{{- end }}
