{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tika
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - image: 6kare/tika2:latest
          name: tika
          ports:
            - containerPort: 9998
              protocol: TCP
{{- end }}
